bashtage/arch

arch/bootstrap/base.py, arch/bootstrap/tests/test_bootstrap.py
Bootstrap apply does not currently work with scalar functions since
it expects the value returned to have a shape attribute.
=> FIX: Make bootstrap work with scalar function

doc/requirements.txt
Notebook conversion currently requires IPython 2
[skip ci]
=> DOC: Require IPython 2 for RTF

doc/source/univariate/introduction.rst
Adds documentation for ARCHModelFixedResult.
[skip ci]
=> DOC: Add ARCHModelFixedResult to docs

arch/univariate/recursions.pyx
Fixed EGARCH recursion in Cython file to not use sigma2 if == INF.
=> Fixing #91 -- egarch bounds check logic reversed

setup.py
'python setup.py clean' fails due to the glob module not being present.
Moved glob import statement to the top of the setup.py file to the top
of the file to allow the clean command to work.
=> Moved glob import in setup.py to make clean command work

arch/bootstrap/multiple_comparrison.py, arch/bootstrap/tests/test_multiple_comparrison.py, doc/source/changes/3.0.txt
Add a p-value of 1.0 for the final model in the MCS.  Previouly
this model had a pvalue of nan.
=> FIX: Add pval for last model in MCS

.travis.yml, README.md, arch/univariate/base.py, setup.py
Change minimum versions for testing to
pandas>=0.14
numpy>=0.18
scipy>=0.14
numba>=0.19
matplotlib>=0.13
This reflects recent releases by all of these projects.
=> UPD: Update minimum versions

doc/source/bootstrap/confidence-intervals.rst, doc/source/bootstrap/low-level-interface.rst, doc/source/bootstrap/parameter-covariance-estimation.rst, doc/source/unitroot/introduction.rst, doc/source/univariate/introduction.rst
`import pandas.io.data as web` no longer works.  Instead, one has to use the outsourced module `pandas_datareader` like so: `import pandas_datareader.data as web`.  On the go, I applied pep8 in the examples.  That is, separate imports from code by one newline and group import statements.
=> DOC: Use pandas_datareader and apply pep8

README.md, arch/bootstrap/tests/test_bootstrap.py, arch/univariate/tests/test_recursions.py, arch/univariate/tests/test_variance_forecasting.py, setup.py
Allow tests to be run even if Cython not used in install
Allow win32 install without special switches
=> BLD: Improve Win32 experience

.travis.yml, README.md, appveyor.yml, arch/univariate/recursions_python.py, arch/univariate/tests/test_mean.py, arch/utility/exceptions.py, requirements.txt
Add travis config to test against Python 3.6
Skip matplotlib if not available for testing
=> TST: Add testing for Python 3.6

arch/bootstrap/base.py, arch/tests/bootstrap/test_bootstrap.py
This should resolve #193 with `np.atleast_1d()`. I tested the case listed in the issue and it worked. 
Let me know what you think.
Thanks.
=> np.atleast_1d() fix for conf_int(method='bca') on scaler inputs.

arch/tests/univariate/test_mean.py, arch/univariate/mean.py
Simplify closed form to use the same path for 0 or more parameters except
where required to be different
=> REF: Simplify closed form when no mean parameters

.travis.yml, arch/compat/numba.py, arch/tests/test_compat.py, arch/tests/univariate/test_recursions.py, setup.py
Improve setup to succeed without Cython.
Show a performance warning when pure Python recusions are being executed.
=> BLD/ENH: Allow building wheels without Cython

arch/tests/univariate/test_forecast.py, arch/univariate/base.py, arch/univariate/mean.py, doc/source/changes/4.0.txt, doc/source/index.rst
Allow random_state to be passed from a mean forecast to facilitate reproducibility
closes #290
=> ENH: Expose random_state in mean forecast

arch/bootstrap/base.py, arch/tests/bootstrap/test_bootstrap.py
Checks bca jackknife against bcaboot package using rpy2. Imports are in the new test function to call out the test dependency. Those can be moved to the top if taken.
=> fix bca calculation

arch/bootstrap/base.py, arch/tests/bootstrap/test_bootstrap.py
Clarify that BCa isn't applicable
=> BUG: Clarify that BCa can't be used with unequal samples

.travis.yml, README.md, README.rst, doc/source/changes/4.0.txt, requirements.txt, setup.py
Make Python 3.6 the minimum supported
=> MAINT: Remove Python 3.5 support

arch/bootstrap/base.py, arch/tests/bootstrap/test_bootstrap.py, doc/source/changes/4.0.txt
extra_kwargs was not being passed into the bca acceleration function
closes #366
=> BUG: Pass extra_kwarg into bca calculations

arch/unitroot/unitroot.py
**Changes**
* correcting Zivot-Andrews's docstring
**Why**
* 'nc' is not a valid value for trend.
=> Updating Zivot-Andrews docstring

doc/source/univariate/forecasting.rst
An equation in forecasting.rst is wrong.
This is insignificant, but I think `t` is correct subscript for this equation, not `t-1`. Could you review and merge if this is the right correction?
Thank you.
=> update an equation in forecasting.rst

pyproject.toml
Hardcoding the numpy version may introduce build errors on old version, e.g.:
https://github.com/numpy/numpy/pull/17906
=> Update Python 3.9 build requirement

arch/univariate/volatility.py
Remove log of backcast which should be already logged
closes #485
=> BUG: Correct backcast for simulation forecast in EGARCH

arch/univariate/distribution.py
The code is correct, whereas the corresponding document is inconsistent.
=> Update a mistake in document of GeneralizedError

arch/unitroot/unitroot.py, doc/source/changes/5.0.txt
Improve lag length method in DFGLS to use OLS rather than
GLS which has poor power far from null
=> ENH: Improve lag length selection in DFGLS

arch/tests/univariate/test_mean.py, arch/univariate/base.py, doc/source/changes/5.0.txt, requirements-dev.txt
Only set name when using pandas
closes #565
=> BUG: Allow NumPy arrays in univariate models

arch/tests/univariate/test_mean.py, arch/univariate/base.py
Remove nans created from lags in arch-lm test
closes #599
=> BUG: Drop nan in arch lm test

doc/requirements.txt
There are 1 security vulnerabilities found in ipython 7
- [CVE-2022-21699](https://www.oscs1024.com/hd/CVE-2022-21699)
Upgrade ipython from 7 to 8.0.1 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade ipython to 8.0.1

arch/vendor/__init__.py, requirements.txt
and removed the required dependency on `property_cached`, since it's optional, and only required for Python 3.7
=> prefer `functools.cached_property` for python >= 3.8

README.md, doc/requirements.txt, pyproject.toml, requirements-dev.txt
Rollback to get conda-forge to work on release 6 branch
=> MAINT: Rollback Cython to 0.29 branch

arch/tests/univariate/test_forecast.py, arch/tests/univariate/test_mean.py, arch/tests/univariate/test_rescale.py, arch/unitroot/_engle_granger.py, arch/unitroot/unitroot.py, arch/univariate/base.py
This fixes several cases of:
```
FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
```
=> Fixed deprecation warning

.coveragerc, arch/compat/numba.py, arch/covariance/kernel.py
Benchmarked using: `py.test arch/tests/unitroot/test_fmols_ccr.py`
Before:
```bash
============================= fixture duration top ============================== 
total          name              num   avg            min
0:00:00.080000             trend  1728        0:00:00 0:00:00
0:00:00.062000              diff  1728        0:00:00 0:00:00
0:00:00.032000            kernel  1728        0:00:00 0:00:00
0:00:00.031000         force_int  1728        0:00:00 0:00:00
0:00:00.016000   trivariate_data     2 0:00:00.008000 0:00:00
0:00:00.016000           x_trend  1728        0:00:00 0:00:00
0:00:00.016000         bandwidth  1728        0:00:00 0:00:00
0:00:00.253000       grand total 10426        0:00:00 0:00:00
============================ test call duration top …
```
=> Sped up covariance estimate via numba

arch/tests/univariate/test_mean.py, arch/univariate/base.py, ci/azure/azure_template_posix.yml
Add early contiguity check
closes #740
=> BUG: Ensure data is always continguous

arch/tests/univariate/test_mean.py, arch/univariate/base.py, arch/univariate/mean.py, arch/univariate/volatility.py, ci/azure/azure_template_posix.yml
Systematically find an fix bugs that affect fixed results
closes #749
=> BUG: Fix bugs in fixed result

arch/tests/univariate/test_forecast.py, arch/univariate/base.py, arch/univariate/mean.py
Add additional test
Fix bug that occurs when simulations=1
closes #749
=> TST: Add tests for fcasts with exog

arch/univariate/volatility.py
E.g. in the original paper of Baililie et al. / Journal of Econometrics 74 (1996) 3-30 at the top o p.14 in the table caption:
$\sigma_t^2 = \omega + [1 - \beta L - (1 - \phi L)(1 - L)^d] R_t^2 + \beta \sigma_{t-1}^2$
so $\phi(L)=1-\phi L$ for first order model.
In ARCH($\infty$) form: 
$\sigma_t^2 = (1 - \beta(L))^{-1} \omega + \lambda(L) R_t^2$ 
where
$\lambda(L) = (1 - (1 - \beta L)^{-1} (1 - \phi L)(1 - L)^d) = \sum_{k=0}^\infty \lambda_k L^k$
Having $1-\phi L$ is necessary for $\lambda_0$ to be 0, as is correctly written in the recursive formulas.
=> bugfix FIGARCH(1, d, 1) formula in the function description

arch/tests/unitroot/test_unitroot.py, arch/tests/univariate/test_distribution.py, arch/tests/univariate/test_mean.py, arch/unitroot/critical_values/simulation/dfgls_critical_values_simulation.py, arch/unitroot/unitroot.py, arch/univariate/base.py, arch/univariate/distribution.py, arch/univariate/mean.py, arch/univariate/volatility.py, ci/azure/azure_template_posix.yml, ci/azure/azure_template_windows.yml, requirements-dev.txt
Reformat where needed
Add additional CI jobs
=> CI: Add Python 3.13 to run

pyproject.toml
Raise upper bound on `setuptools-scm` dependency from `9` to `9.3`.
=> Raise upper bound on setuptools-scm from 9 to 9.3
