bashtage/arch

- arch/bootstrap/base.py
- arch/univariate/mean.py
Add meaningful str and repr for bootstraps.  Also fixes issue in arch reprs.
> ENH: Improve str and repr for bootstrap

- arch/bootstrap/base.py
- arch/bootstrap/tests/test_bootstrap.py
Add tests for bootstrap str and repr
> TST: Add tests for str and repr

- arch/univariate/tests/test_recursions.py
Add performance test for Numba relative to Cython to detect any breaks due 
to Numba changes
> TST: Add performance test for Numba code

- arch/bootstrap/__init__.py
- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparrison.py
- arch/bootstrap/tests/test_bootstrap.py
- arch/bootstrap/tests/test_multiple_comparrison.py
- arch/compat/python.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_large_cluster.py
- arch/utility/timeseries.py
- arch/utils.py
- doc/source/bootstrap/bootstrap.rst
- doc/source/bootstrap/multiple-comparison.rst
Adds White/Hansen Test of Superior Predictive Ability and
Romano and Wolf's StepM procedure
> ENH: Add multiple comparison procedures

- arch/bootstrap/tests/test_multiple_comparrison.py
- arch/unitroot/tests/test_unitroot.py
Removed unnecessary printing in tests
> TST: Remove unneeded printing in tests

- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparrison.py
- arch/bootstrap/tests/test_multiple_comparrison.py
Adds formal testing for SPA and StepM multiple comparison proedures
> TST: Add formal tests for multiple comparisons

- README.md
- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparrison.py
- arch/bootstrap/tests/test_multiple_comparrison.py
- arch/univariate/tests/test_mean.py
Add additional formal tests of SPA and StemM
> TST: Improve multiple comparison testing

- doc/source/bootstrap/background.rst
- doc/source/bootstrap/bootstrap.rst
- doc/source/index.rst
- doc/source/multiple-comparison/background.rst
- doc/source/multiple-comparison/multiple-comparison-reference.rst
- doc/source/multiple-comparison/multiple-comparisons.rst
- examples/multiple-comparison_examples.ipynb
Promote multiple comparisons to a stand alone section
Reorganize ipython notebooks
General documentation cleanup
> DOC: Reorganize documentation for multiple comparisons

- README.md
- arch/bootstrap/multiple_comparrison.py
- arch/bootstrap/tests/test_multiple_comparrison.py
Tests edge cases and incorrect usage.
Added error messages for some incorrect usage
> TST: Add tests and protections for edge cases

- building/binstar/meta.yaml
- building/binstar_unix.sh
- building/binstar_windows.bat
- building/python2_setup.bat
Improvements to binstar building.
[skip ci]
> BLD: Improve binstar build files

- doc/requirements.txt
> DOC: Attempt to fix build on read the docs

- .idea/dictionaries/ksheppard.xml
> CLN: Remove unneeded file

- arch/bootstrap/multiple_comparrison.py
- arch/unitroot/critical_values/__init__.py
- arch/unitroot/tests/__init__.py
- arch/unitroot/unitroot.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
- arch/univariate/tests/test_mean.py
- arch/univariate/volatility.py
- arch/utility/array.py
- arch/utility/timeseries.py
- requirements.txt
Add hedgehog plot to visualize forecasts over time
> ENH: Hedgehog plot

- doc/requirements.txt
- doc/source/conf.py
Update sphinx to 1.3 and remove dependence on contrib-napoleon
> DOC: Update Sphinx to 1.3

- doc/requirements.txt
Update rquirements for RTD
[skip ci]
> DOC: Update for RTD build

- doc/source/conf.py
Output versions to understand RTD build problems
[skip ci]
> DOC: FIX RTD bugs

- setup.py
Code to debug RTD problems
[skip ci]
> DOC: Debug RTD

- doc/requirements.txt
Attempt fix for RTD by adding more information to ipython in
requirements
[skip ci]
> DOC: Fixed for RTD

- arch/univariate/base.py
- doc/source/univariate/introduction.rst
Adds details explaining how to interpret the output of the forecasting
function.
closes #60
[skip ci]
> DOC: Further explanation for forecasting

- .travis.yml
- arch/univariate/tests/test_volatility.py
- arch/univariate/volatility.py
Incorrect power was used to initialize simulation.
closes #62
> FIX: Fix initial value for GARCH simulation

- .travis.yml
- arch/bootstrap/tests/test_bootstrap.py
Update numba to latest for testing
> TST: Update numba for testing

- arch/unitroot/unitroot.py
- examples/unitroot_examples.ipynb
Hi, 
I spotted some typos and extra words while reading the doc. Here are my corrections.
Have a nice day.
> DOC: typos.

- arch/univariate/base.py
Accidentally removed sigma2 init code in early PR
closes #94
> FIX: Restore variance initialization code

- .travis.yml
Add test config for numpy 1.10 and python 3.5
> TST: Add config for new numpy and python

- arch/utility/array.py
Workaround for deprecation warnings in current pandas
> FIX: Avoid deprecation warnings due to pandas changes

- arch/bootstrap/tests/test_multiple_comparrison.py
Add tests for exact ties in the MCS.
closes #97
> TST: Add tests for exact ties in MCS

- .travis.yml
> TST: Fix travis to reflect changes in miniconda

- arch/bootstrap/tests/test_multiple_comparrison.py
Ensure index is integer type in test
> TST: Fix test erroneously using floats

- .travis.yml
- setup.py
Remove IPython imports in favor of new locations
> UPD: Update notebook functions to jupyter

- .landscape.yml
- .travis.yml
- README.md
- appveyor.yml
Add testing on appveyor
Update travis recipe
> TST: Add appveyor

- .travis.yml
- ci/statsmodels-master.sh
Add a test against statsmodels master to prevent surprises
> TST: Add test against statsmodels master

- arch/unitroot/unitroot.py
- arch/univariate/mean.py
Fix formatting and other small errors so that module passes doctests
> DOC: Fix docs to pass doctest

- arch/univariate/tests/test_mean.py
- arch/utility/array.py
Fix naming issue when using numpy data
Add test for bug reported about variable names
> BUG: Fix naming issue for numpy array input

- .travis.yml
- arch/__init__.py
- arch/bootstrap/__init__.py
- arch/compat/numba.py
- arch/compat/python.py
- arch/unitroot/unitroot.py
- arch/univariate/__init__.py
- arch/univariate/base.py
- arch/univariate/volatility.py
- arch/utility/array.py
Clean flake8 identified errors
Use nosetests for test runs
Add testing to travis
> TST: Add flake8 testing

- appveyor.yml
Add depth to appveyor config
Small modification to method of testing
> TST: Appveyor config

- arch/univariate/tests/test_volatility.py
Test __str__ and __repr__
Add test for value errors
> TST: Add tests for strings and errors

- .travis.yml
Add initial support for codecov
> TST: Add codecov support

- .travis.yml
- arch/bootstrap/tests/test_bootstrap.py
- arch/bootstrap/tests/test_multiple_comparrison.py
- arch/unitroot/tests/test_unitroot.py
- arch/univariate/tests/test_distribution.py
- arch/univariate/tests/test_mean.py
- arch/univariate/tests/test_recursions.py
- arch/univariate/tests/test_volatility.py
- arch/utility/tests/test_array.py
- arch/utility/tests/test_cov.py
- arch/utility/tests/test_timeseries.py
- doc/requirements.txt
- requirements.txt
> TST: Switch to using py.test

- README.md
- building/README.md
- building/binstar_unix.sh
- building/binstar_windows.bat
Update readme and binstar recipes
[skip ci]
> DOC: Update readme and binstar

- arch/univariate/base.py
- arch/univariate/tests/test_mean.py
Add show_warning flag to fit which will allow the warning to be suppressed
closes #124
> ENH: Add flag to allow warning filtering

- .travis.yml
- arch/compat/pandas.py
- arch/univariate/tests/test_distribution.py
- arch/univariate/tests/test_mean.py
- arch/univariate/tests/test_recursions.py
- arch/univariate/tests/test_volatility.py
- arch/utility/array.py
- arch/utility/tests/test_timeseries.py
Reformat use of unittest
Remove unnecessary unittest runner code
Move pandas compatability code to own module
Fix issue preventing coverage
> CLN: Clean up testing code

- .travis.yml
- README.md
- arch/bootstrap/tests/test_bootstrap.py
- arch/bootstrap/tests/test_multiple_comparrison.py
- arch/unitroot/tests/test_unitroot.py
- arch/univariate/tests/test_distribution.py
- arch/univariate/tests/test_mean.py
- arch/univariate/tests/test_recursions.py
- arch/univariate/tests/test_volatility.py
- arch/utility/tests/test_array.py
- arch/utility/tests/test_cov.py
- arch/utility/tests/test_timeseries.py
- doc/source/univariate/mean.rst
Enforce PEP8 checks for testing code
> CLN: Enforce PEP8 for tests

- arch/univariate/distribution.py
- setup.cfg
Backport documentation fixes from variance forecasting
Change flake8 to 100 characters
> CLN: Backport documentation fixes

- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparrison.py
- arch/unitroot/critical_values/dickey_fuller.py
- arch/unitroot/unitroot.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
- arch/utility/array.py
Ensure consistency of compat imports at top of file
> CLN: Consolidate the compat imports

- .travis.yml
Move coverage so 3.5 and 2.7 are covered
> TST: Move coverage to 2.7 branch

- arch/univariate/tests/test_forecast.py
Reduce data size to allow 32-bit tests to pass
> TST: Reduce test size to allow 32-bit tests

- arch/univariate/tests/test_mean.py
- arch/univariate/tests/test_variance_forecasting.py
- arch/univariate/tests/test_volatility.py
Complete ARCH(1) test
Add minimal tests for EGARCH forecast
> TST: Complete ARCH test

- arch/univariate/base.py
- arch/univariate/tests/test_mean.py
Add volatility option to hedge hog plot
> ENH: Update hedgehog plot to plot mean or volatility

- arch/univariate/tests/test_variance_forecasting.py
- arch/univariate/volatility.py
Add path for simulation forecasting of EGARCH models
Add smoke tests of code
> ENH: Add EGARCH simulation/bootstrap forecasting

- arch/univariate/base.py
- arch/univariate/mean.py
- arch/univariate/tests/test_forecast.py
- arch/univariate/tests/test_mean.py
Add tests for first and last observation
Add tests for equivalence with other methods
> REF: Refactor first and last obs to return values

- arch/bootstrap/tests/test_bootstrap.py
- arch/bootstrap/tests/test_multiple_comparrison.py
- arch/univariate/tests/test_variance_forecasting.py
- arch/univariate/volatility.py
- arch/utility/tests/test_array.py
Add formal tests for egarch and rm2006 models
Clean up test_array
Remove unnecessary smoke tests
> TST: Add egarch and rm2006 tests

- .travis.yml
- appveyor.yml
Enable parallel test execution
> TST: Parallel test execution

- arch/unitroot/tests/test_unitroot.py
- arch/unitroot/unitroot.py
Improve performance for lag length selection by avoiding multiple
calls to OLS
> ENH: Improve performnace for lag length selection

- arch/univariate/base.py
- arch/univariate/mean.py
- arch/univariate/tests/test_mean.py
- arch/univariate/tests/test_variance_forecasting.py
- arch/univariate/tests/test_volatility.py
- arch/univariate/volatility.py
Add a fixed variance process to enable fitting mean models with
pre-specificed variances.
> ENH: Add fixed variance process

- arch/univariate/recursions.pyx
- arch/univariate/recursions_python.py
Prevent variance from going negative by only taking log of number
greater than or equal to 1
closes #150
> BUG: Fix error in variance bound violation

- arch/univariate/__init__.py
- doc/source/univariate/volatility.rst
Add FixedVariance to documentation
Expose FixedVariance in arch.univariate
[skip ci]
> DOC: Add FixedVariance to documentation

- arch/univariate/base.py
- arch/univariate/tests/test_mean.py
- doc/source/changes/4.0.txt
- doc/source/conf.py
Fix regression in fix that was introduced when first_ and last_obs
were added
Add first_obs and last_obs options to fix
Add test for these cases
closes #156
> BUG: Fix doesn't work with new models

- .travis.yml
- doc/requirements.txt
- doc/source/conf.py
Update Python 3.6 to use numba
Add numpydoc to sphinx
> TST/DOC: Improve travis and doc generation

- doc/source/bootstrap/bootstrap.rst
- doc/source/multiple-comparison/multiple-comparison-reference.rst
- doc/source/unitroot/tests.rst
- doc/source/univariate/distribution.rst
- doc/source/univariate/mean.rst
- doc/source/univariate/volatility.rst
Add locations so that py-modindex is generated
[skip ci]
> DOC: Add module index locations

- .travis.yml
- README.md
- appveyor.yml
- arch/univariate/tests/test_recursions.py
- ci/performance.py
- requirements.txt
- setup.py
Add performance testing outside of formal test
Update travis for more modern config
> PERF: Add seperate performance testing

- arch/compat/numba.py
Enable fastmath for numba jit code
> PERF: Enable fastmath for numba

- arch/__init__.py
- arch/bootstrap/__init__.py
- arch/bootstrap/_samplers_python.py
- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparrison.py
- arch/bootstrap/tests/test_multiple_comparrison.py
- arch/unitroot/__init__.py
- arch/unitroot/critical_values/dickey_fuller.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_large_cluster.py
- arch/unitroot/critical_values/simulation/dfgls_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/kpss_critical_values_simulation.py
- arch/unitroot/unitroot.py
- arch/univariate/__init__.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
- arch/univariate/recursions_python.py
- arch/univariate/tests/test_forecast.py
- arch/univariate/volatility.py
- arch/utility/__init__.py
- arch/utility/array.py
- arch/utility/cov.py
- arch/utility/tests/test_cov.py
- arch/utility/tests/test_timeseries.py
Add absolute import ot improve cross Python compat
> COMPAT: Att absolute import

- arch/univariate/volatility.py
Change power in starting value intercept scale
closes #168
> BUG: Change starting values scale to improve accuracy

- arch/univariate/mean.py
- arch/utility/array.py
- setup.py
Ensure variable is set
Ensure file is closed
> CLN: Silence small warnings

- arch/bootstrap/__init__.py
- arch/unitroot/critical_values/simulation/kpss_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/kpss_simulation_process.py
Improve simulation to improve resolution for small pvals
Update so that it works in current python
Fix small LGTM issue with bootstrap init
> ENH: Improve KPSS crit val simulation

- .travis.yml
Update travis to include matplotlib
> TST: Update travis

- doc/source/univariate/forecasting.rst
- examples/univariate_volatility_modeling.ipynb
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> Correct doc typos

- arch/bootstrap/multiple_comparrison.py
- arch/tests/bootstrap/test_multiple_comparrison.py
- doc/source/changes/4.0.txt
Fix bug where final included model was not included
> BUG: Fix bug in MCS for max method

- arch/tests/univariate/test_distribution.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/volatility.py
- doc/source/univariate/distribution.rst
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> Rename loglikelihoood to loglikelihood

- arch/tests/univariate/test_mean.py
- arch/univariate/base.py
- arch/univariate/recursions.pyx
- arch/univariate/recursions_python.py
Show summary when a results instance is repr'd
> ENH: Switch repr of results to summary

- arch/tests/univariate/test_volatility.py
- arch/univariate/volatility.py
- doc/source/changes/4.0.txt
- examples/univariate_volatility_modeling.ipynb
Allow estimation of EWMA variance parameter along with other model
parameters
> ENH: Allow estimation of EWMA Variance parameters

- .coveragerc
- .travis.yml
- setup.py
> BLD: Add coverage of Cython code

- arch/tests/univariate/test_mean.py
- arch/univariate/base.py
- arch/univariate/mean.py
- doc/source/changes/4.0.txt
Refactor to use generic scipy interface
Allow options to be set by the user
closes #195
> ENH: Allow optimization options

- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparison.py
- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/bootstrap/test_multiple_comparison.py
- arch/tests/univariate/test_distribution.py
- arch/tests/univariate/test_forecast.py
- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/unitroot/unitroot.py
- arch/univariate/__init__.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
- arch/univariate/volatility.py
- arch/utility/array.py
- arch/utility/cov.py
- doc/source/changes/4.0.txt
- doc/source/univariate/distribution.rst
Add GED distribution
Allow 1-step forecasting with exog
Typos
closes #198
> Add ged distn

- .travis.yml
- LICENSE.md
- arch/tests/univariate/test_mean.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
Add path for GED
Update license
Fix small warning issue in SKewT
> BUG: Ensure GED is used in arch_model

- arch/tests/univariate/test_mean.py
- doc/source/univariate/forecasting.rst
- doc/source/univariate/introduction.rst
Fix incorrect subscripts
closes #207
> DOC: Fix wrong subscripts

- arch/bootstrap/multiple_comparrison.py
- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/bootstrap/test_multiple_comparison.py
- arch/tests/unitroot/test_unitroot.py
- arch/tests/univariate/test_distribution.py
- arch/tests/univariate/test_forecast.py
- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_recursions.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/tests/univariate/test_volatility.py
- arch/tests/utility/test_array.py
- arch/tests/utility/test_cov.py
- arch/tests/utility/test_timeseries.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_large_cluster.py
- arch/unitroot/critical_values/simulation/dfgls_critical_values_simulation.py
- arch/univariate/distribution.py
- arch/univariate/volatility.py
- doc/source/changes/4.0.txt
Remove calls to global RandomState object
> MAINT: Remove use of global RandomState

- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_recursions.py
- arch/tests/utility/test_array.py
- arch/univariate/recursions_python.py
- arch/utility/array.py
> TST: Improve coverage of utility

- .travis.yml
- README.md
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_large_cluster.py
- arch/unitroot/critical_values/simulation/dfgls_critical_values_simulation.py
- arch/univariate/mean.py
- requirements.txt
- setup.py
Fix small errors and bad smells.
> Fix small errors

- arch/tests/univariate/test_volatility.py
- arch/unitroot/unitroot.py
Add column names to regression results in DF-type tests
> ENH: Add column names to regression results in ADF

- .travis.yml
- README.md
- doc/source/changes/4.0.txt
Update change log with latest changes
> DOC: Update change log

- .gitignore
- .travis.yml
- doc/source/bootstrap/bootstrap.rst
- doc/source/conf.py
- doc/source/multiple-comparison/multiple-comparisons.rst
- doc/source/unitroot/unitroot.rst
- doc/source/univariate/univariate.rst
Simplify setup by using nbsphinx to handle notebooks
> DOC: Switch to nbshpinx

- .travis.yml
- setup.py
> Optional mpl

- arch/compat/python.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/dfgls_critical_values_simulation.py
- arch/unitroot/unitroot.py
- arch/univariate/base.py
- arch/univariate/mean.py
- arch/univariate/recursions_python.py
- doc/source/changes/4.0.txt
Use a QR based algorithm in autolag to improve performance
Remove two types of imports
Strip compat to the minimum
> ENH: Speed up autolag in ADF

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- arch/univariate/mean.py
- doc/source/changes/4.0.txt
- large-data.py
Add method that limits memory usage for long time series
> ENH: Add low memory autolag method

- README.rst
- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/bootstrap/test_multiple_comparison.py
- arch/tests/unitroot/test_unitroot.py
- arch/tests/univariate/test_mean.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/kpss_critical_values_simulation.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
Fix small issues in code that can be avoided
> CLN: Small improvements to code quality

- .travis.yml
- arch/univariate/base.py
- arch/univariate/mean.py
- doc/requirements.txt
- requirements.txt
- setup.py
Use cached_property instead of cache_readonly
> MAINT: Improve caching

- .travis.yml
Remove conda-forge from docbuild downloads
> DOC: Remove conda-forge

- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/unitroot/critical_values/dickey_fuller.py
- arch/univariate/volatility.py
Remove unused iteration variables and related bug bears
> CLN: Remove small bug bears

- .travis.yml
- README.rst
- arch/tests/univariate/test_recursions.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/tests/univariate/test_volatility.py
- arch/univariate/__init__.py
- arch/univariate/base.py
- arch/univariate/mean.py
- arch/univariate/recursions.pyx
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
- arch/utility/exceptions.py
- doc/source/bootstrap/background.rst
- doc/source/conf.py
- doc/source/univariate/volatility.rst
- setup.cfg
Add MIDAS hyperbolic processes
Test corner cases of recursions and fix small issue
Improve recusions performance by forcing C-alignment
> ENH/CLN/TST: Add MIDAS processes

- .travis.yml
Improve travis syntax and simplify
> BLD: Update travis syntax

- .coveragerc
- arch/bootstrap/_samplers_python.py
- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparison.py
- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/bootstrap/test_multiple_comparison.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/unitroot/unitroot.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
- arch/univariate/volatility.py
- arch/utility/array.py
Improve docstrings
Clarify ndarray over array
List pandas types where accepted
> DOC: Clarify and improve docstrings

- .coveragerc
- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/unitroot/test_unitroot.py
- arch/tests/utility/test_array.py
- arch/unitroot/unitroot.py
Improve corner case coverage
Simplify bootstrap testing by using a common function
> TST/CLN: Improve corner case coverage

- README.md
- README.rst
- arch/compat/python.py
- arch/tests/univariate/test_mean.py
- arch/unitroot/critical_values/simulation/kpss_simulation_process.py
- arch/univariate/base.py
- lgtm.yml
- setup.py
Clean python compat file to remove unnecessary StringIO
Configure lgtm
> CLN/BLD: Improve inspections

- .coveragerc
- .travis.yml
- appveyor.yml
- arch/univariate/base.py
- arch/univariate/mean.py
- arch/vendor/__init__.py
- arch/vendor/cached_property.py
- setup.cfg
Vendorize cached_property to help wit conda building
> MAINT: Vendor cached_property

- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/volatility.py
- arch/utility/array.py
Switch to ADSI rather than DSI
Update DocStringInheritor to work with Python 2.7 properties
> REF: Switch to AbstractDocStringInheritor

- doc/source/bootstrap/iid-bootstraps.rst
- doc/source/bootstrap/timeseries-bootstraps.rst
- doc/source/multiple-comparison/multiple-comparison-reference.rst
- doc/source/unitroot/tests.rst
- doc/source/univariate/distribution.rst
- doc/source/univariate/introduction.rst
- doc/source/univariate/mean.rst
- doc/source/univariate/volatility.rst
- requirements.txt
> DOC: Small doc formatting

- arch/tests/univariate/test_mean.py
- arch/univariate/base.py
- arch/univariate/mean.py
- arch/univariate/recursions.pyx
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
Add user ability to set backcast
Fix bug where models with 0 parameters were treated as having parameters
> ENH/BUG: Add ability for user to set backcast

- arch/univariate/base.py
https://lgtm.com/projects/g/bashtage/arch/alerts?mode=list
> Correct deepcopy import

- .coveragerc
- .travis.yml
- appveyor.yml
- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_recursions.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/tests/univariate/test_volatility.py
- arch/univariate/__init__.py
- arch/univariate/mean.py
- arch/univariate/recursions.pyx
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
- ci/performance.py
- doc/source/changes/4.0.txt
- doc/source/univariate/volatility.rst
- setup.py
Add FIGARCH volatility process
> ENH: Add FIGARCH volatility process

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- doc/source/changes/4.0.txt
Ensure that ADF autolag has sufficient observations in short time series
closes #262
> BUG: Ensure ADF has sufficient obs

- arch/tests/univariate/test_mean.py
- arch/univariate/base.py
- arch/utility/testing.py
- doc/source/changes/4.0.txt
- doc/source/univariate/introduction.rst
- doc/source/univariate/univariate.rst
- doc/source/univariate/utility.rst
Add ARCH LM test to model results
closes #261
> ENH: Add ARCH LM test

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- doc/source/changes/4.0.txt
Add KPSS autolag method to use data-dependent lag selection
xref statsmodels/statsmodels#5522
> ENH: Add KPSS autolag method

- appveyor.yml
Remvoe test path pin on Windows
[skip travis]
> TST: Fix failure on appveyor

- arch/__init__.py
- arch/utility/__init__.py
- pyproject.toml
Enable pytest to be run from installed package using a .test() function
> BLD: Use pyargs to test

- .travis.yml
- arch/utility/__init__.py
Add coverage for code the requires numba to be absent
> BLD: Add covered build without numba

- arch/utility/array.py
Ensure timezone information is normalized before comparrisons are made
> MAINT: Fix future warning in datetime

- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/tests/univariate/test_volatility.py
- arch/univariate/__init__.py
Fix import locations to make sure corrrect module is imported
> BUG: Fix import locations

- .travis.yml
- arch/utility/__init__.py
Use test to ensure package can be tested from an installations
> BLD: Use test in testing

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
Fix variance for overlapping variance estiamtors
> BUG: Fix bugs in VarianceRatio

- arch/tests/univariate/test_mean.py
- arch/univariate/__init__.py
- arch/univariate/base.py
- arch/utility/array.py
- doc/source/changes/4.0.txt
Expose optimization results to allow end users to verify convergence
> ENH: Expose optimzation results

- arch/bootstrap/base.py
- arch/tests/bootstrap/test_bootstrap.py
- doc/source/changes/4.0.txt
Use the mean fo teh jackknife samples instead of the original estimte
closes #288
> BUG: Fix center for loo jackknife

- arch/tests/univariate/test_distribution.py
- arch/tests/univariate/test_mean.py
- arch/univariate/distribution.py
- doc/source/conf.py
- setup.py
Require parameters for cdf and ppf
closes #295
> ENH: Clarify need for parameters

- arch/bootstrap/base.py
- arch/compat/statsmodels.py
- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/unitroot/test_unitroot.py
- arch/tests/univariate/test_mean.py
- arch/tests/utility/test_cov.py
Silence some test noise
Make some functions as private
> MAINT: Clean up test noise

- .travis.yml
- README.md
- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparison.py
- arch/compat/python.py
- arch/tests/unitroot/test_unitroot.py
- arch/tests/univariate/test_forecast.py
- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_recursions.py
- arch/tests/univariate/test_volatility.py
- arch/tests/utility/test_array.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_large_cluster.py
- arch/unitroot/critical_values/simulation/dfgls_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/dfgls_simulation_process.py
- arch/unitroot/unitroot.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
- arch/utility/array.py
- doc/source/changes/4.0.txt
- doc/source/conf.py
- doc/source/images/color-logo.svg
- doc/source/images/favicon.py
- doc/source/images/hero.py
- doc/source/index.rst
- requirements.txt
- setup.py
Remove 2.7 compat shims
Improve the docs
> ENH: Remove Python 2.7 compat

- arch/tests/univariate/test_mean.py
- arch/univariate/base.py
- doc/source/changes/1.0.txt
- doc/source/changes/2.0.txt
- doc/source/changes/3.0.txt
- doc/source/changes/4.0.txt
Fix a big that assumed input was a pandas Series
closes #313
> BUG: Fix a bug in arch_lm_test

- arch/bootstrap/base.py
- arch/tests/bootstrap/test_bootstrap.py
- arch/utility/exceptions.py
- doc/source/changes/4.0.txt
Ensure covariance is positive and meaningfully large
> ENH: Add check for 0 covariance in studentization

- arch/bootstrap/base.py
- arch/tests/bootstrap/test_bootstrap.py
- arch/utility/exceptions.py
- doc/source/changes/4.0.txt
Raise if inputs are not ndarray, DataFrame or Series
closes #315
> ENH: Enforce type when creating bootstraps

- arch/tests/univariate/test_mean.py
- arch/univariate/base.py
- doc/source/univariate/introduction.rst
- doc/source/univariate/results.rst
Improve results doc by moving to stand alone pages
Add std_resid property to resutls
closes #325
> ENH/DOC: Add std_resid and improve result doc

- arch/unitroot/unitroot.py
https://lgtm.com/projects/g/bashtage/arch/alerts?mode=list
> Clean duplicate import

- arch/tests/univariate/test_mean.py
- arch/univariate/base.py
- doc/source/changes/4.0.txt
- versioneer.py
Add check for positive variance to prevent overflow.
closes #331
> BUG: Prevent overflow when variance is 0

- .codacy.yml
- ci/performance.py
- doc/source/conf.py
- doc/source/images/favicon.py
- doc/source/images/hero.py
- setup.py
- versioneer.py
> ENH: Add codacy config

- arch/typing.py
- arch/univariate/base.py
- arch/univariate/mean.py
- arch/univariate/volatility.py
- setup.py
> CLN: Add typing to base

- arch/_version.py
- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparison.py
- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/bootstrap/test_multiple_comparison.py
- arch/tests/unitroot/test_unitroot.py
- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_moment.py
- arch/tests/univariate/test_recursions.py
- arch/tests/univariate/test_volatility.py
- arch/typing.py
- arch/unitroot/critical_values/simulation/kpss_critical_values_simulation.py
- arch/unitroot/unitroot.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
- arch/univariate/recursions.pyx
- arch/univariate/volatility.py
- arch/utility/__init__.py
- arch/utility/array.py
- arch/utility/timeseries.py
Add typing to volatilty
Loosen typing where possible
COmplete typing for arch
> CLN: Add typing to volatility

- arch/bootstrap/base.py
- arch/data/binary/__init__.py
- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_moment.py
- arch/unitroot/critical_values/simulation/dfgls_simulation_process.py
- arch/unitroot/unitroot.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
Iterate accross typing to improve type info
> CLN: Improve typing

- README.md
- doc/source/changes/4.0.txt
> DOC: Finalize changes for 4.12 release

- arch/univariate/base.py
- arch/univariate/mean.py
- arch/utility/array.py
- arch/utility/testing.py
- arch/vendor/__init__.py
- arch/vendor/property_cached.py
> MAINT: Revert vendored property_cached

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- doc/source/changes/4.0.txt
- setup.cfg
Make change to allow simplifiation
> REF: Make unit root tests immutable

- arch/compat/statsmodels.py
- arch/covariance/kernel.py
- arch/tests/unitroot/test_dynamic_ols.py
- arch/tests/utility/test_io.py
- arch/unitroot/__init__.py
- arch/unitroot/cointegration.py
- arch/unitroot/critical_values/simulation/kpss_critical_values_simulation.py
- arch/unitroot/unitroot.py
- arch/utility/io.py
- arch/utility/timeseries.py
- doc/source/unitroot/cointegration.rst
- setup.cfg
Continue from #320 and add DynamicOLS
> ENH: Add DynamicOLS

- arch/tests/unitroot/test_dynamic_ols.py
- arch/tests/unitroot/test_engle_granger.py
- arch/tests/utility/test_timeseries.py
- arch/unitroot/cointegration.py
- arch/unitroot/critical_values/simulation/engle_granger_simulation.py
- arch/utility/timeseries.py
- doc/source/images/favicon.py
- setup.cfg
- setup.py
- versioneer.py
Ensure trend is after x variables
> ENH: Reorder variables

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- arch/utility/exceptions.py
- doc/source/changes/4.0.txt
Improve error message when test cannot be run due to issues
in user provided data
xref #364
> ENH: Improve error message for ADF

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- doc/source/changes/4.0.txt
Improve user-facing exceptions in Phillips-Perron test
xref #364
> ENH: Improve exceptions for Phillips-Perron

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- doc/source/changes/4.0.txt
Improve user-facing exceptions in KPSS test
xref #364
> ENH: Improve exceptions for KPSS

- arch/tests/bootstrap/test_bootstrap.py
> TST: Test edge cases in bootstrap

- .travis.yml
- doc/source/index.rst
Add an explicit devel doc build
> MAINT: Add a devel doc build

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- doc/source/changes/4.0.txt
Improve user-facing exceptions in Zivot-Andrews test
xref #364
> ENH: Improve exceptions for Zivot-Andrews

- arch/bootstrap/base.py
- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/_phillips_ouliaris.py
- arch/unitroot/unitroot.py
- arch/univariate/mean.py
- arch/utility/cov.py
Add user protections in Variance Ratio
> ENH: Improve Variance Ratio

- .travis.yml
- doc/source/changes/4.0.txt
> DOC: Update changes

- .travis.yml
- arch/tests/unitroot/cointegration_data.py
- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- setup.cfg
> MAINT: Ensure test runner is used

- .travis.yml
- arch/tests/utility/test_utility.py
- arch/utility/__init__.py
Ensure runner is used
Prevent recursive running
> MAINT: Fix coverage with test runner

- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation.py
- arch/utility/__init__.py
Make simulation restartable so that interruption is less costly
> MAINT: Improve simulation

- arch/tests/utility/test_array.py
> TST: Enable doc test

- .travis.yml
- arch/tests/univariate/test_rescale.py
- ci/travis-osx-setup.sh
> TST: Add a test run on OSX

- arch/tests/univariate/test_mean.py
- arch/univariate/mean.py
> ENH: Allow 1d exog

- arch/tests/unitroot/test_engle_granger.py
- arch/tests/univariate/test_forecast.py
- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/engle_granger_simulation.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation.py
- arch/unitroot/unitroot.py
- arch/univariate/base.py
- arch/univariate/mean.py
- arch/univariate/volatility.py
- setup.cfg
Check that horizon is an int >= 1
> ENH: Add explicit error for bad horizon

- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
Add regression results
closes #395
> ENH: Add regression results to Phillips-Perron test

- arch/bootstrap/_samplers.pyx
- arch/tests/test_examples.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_large_cluster.py
- arch/unitroot/critical_values/simulation/adf_z_simlation_process.py
- arch/unitroot/critical_values/simulation/engle_granger_simulation.py
- arch/unitroot/critical_values/simulation/engle_granger_simulation_process.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation-process.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation.py
- arch/univariate/base.py
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
- setup.cfg
- setup.py
Import setuptools to avoid warnings and other issues
> MAINT: Import setuptools first

- appveyor.yml
- arch/univariate/recursions_python.py
- requirements-dev.txt
Revers square due to bug in numba 0.50.x
> MAINT: Revert square

- arch/tests/univariate/test_mean.py
- arch/univariate/mean.py
Clarify how 2D is used and add test
closes #411
> BUG: Correct 2d model initializatiion in HAR

- arch/bootstrap/base.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation.py
- arch/univariate/volatility.py
- arch/utility/testing.py
Update typing for new errors due to mypy changes
> MAINT: Update for changes in mypy

- arch/bootstrap/base.py
- arch/tests/univariate/test_mean.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation.py
- arch/utility/testing.py
> MAINT: Update to black 20.8b1

- ci/azure/azure_template_posix.yml
- ci/install-statsmodels-master.sh
> MAINT: Add statsmodels master build

- arch/tests/univariate/test_mean.py
- arch/univariate/base.py
Use mean model rather than total parameters
closes #319
> BUG: Correct DF Model

- arch/unitroot/unitroot.py
Improve example for VarianceRatio
closes #439
> DOC: Improve doc string example

- arch/tests/univariate/test_mean.py
Add test that backcast is correct
> TEST: Add test that backcast is correct

- arch/tests/univariate/test_recursions.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/tests/univariate/test_volatility.py
- arch/unitroot/critical_values/simulation/adf_simulation.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_large_cluster.py
- arch/unitroot/critical_values/simulation/adf_z_simlation_process.py
- arch/unitroot/critical_values/simulation/dfgls_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/engle_granger_simulation.py
- arch/unitroot/critical_values/simulation/engle_granger_simulation_process.py
- arch/unitroot/critical_values/simulation/kpss_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation-process.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation.py
- arch/unitroot/critical_values/simulation/shared.py
- arch/univariate/__init__.py
- arch/univariate/mean.py
- arch/univariate/recursions.pyx
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
- doc/source/changes/4.0.txt
- doc/source/univariate/volatility.rst
> ENH: Add APARCH volatility process

- arch/tests/test_examples.py
- arch/tests/univariate/test_volatility.py
- arch/univariate/volatility.py
- setup.cfg
Add restriction that allows common asymmetry
> ENH: Add common asymmetry

- arch/univariate/recursions.pyx
> MAINT: Fix isorting

- arch/unitroot/critical_values/simulation/kpss_simulation_process.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation-process.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation.py
Update for latest NumPy and mypy
> MAINT: MyPy fixes

- arch/bootstrap/base.py
- arch/bootstrap/multiple_comparison.py
- arch/compat/numba.py
- arch/covariance/kernel.py
- arch/tests/unitroot/test_phillips_ouliaris.py
- arch/tests/unitroot/test_unitroot.py
- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_rescale.py
- arch/tests/univariate/test_variance_forecasting.py
- arch/unitroot/critical_values/simulation/adf_simulation.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_large_cluster.py
- arch/unitroot/critical_values/simulation/dfgls_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/kpss_critical_values_simulation.py
- arch/unitroot/critical_values/simulation/phillips-ouliaris-simulation.py
- arch/unitroot/unitroot.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
- arch/univariate/volatility.py
- arch/utility/array.py
- arch/utility/exceptions.py
- arch/utility/testing.py
- arch/utility/timeseries.py
- arch/vendor/property_cached.py
- setup.cfg
> ENH: Improve typing

- README.md
Replace anaconda.org with conda forge
> MAINT: Update badge

- arch/tests/univariate/test_mean.py
- arch/univariate/base.py
- doc/source/changes/4.0.txt
> BUG: Fix error in EWMA Conditional Volatility

- arch/tests/univariate/test_forecast.py
- ci/azure/azure_template_posix.yml
> MAINT: Skip slow tests on coverage

- arch/tests/covariance/test_covariance.py
- arch/tests/unitroot/test_unitroot.py
- arch/tests/univariate/test_forecast.py
More coverage of branches and esges
> MAINT: Improve coverage

- arch/bootstrap/base.py
- arch/tests/bootstrap/test_bootstrap.py
- arch/tests/univariate/test_variance_forecasting.py
- ci/azure/azure_template_posix.yml
> TST: Add test for corner cases

- arch/tests/test_examples.py
- arch/tests/unitroot/test_phillips_ouliaris.py
- arch/tests/unitroot/test_unitroot.py
- arch/tests/utility/test_array.py
- arch/tests/utility/test_timeseries.py
- arch/utility/__init__.py
- arch/utility/array.py
> TST: Add coverage for additional corner cases

- .coveragerc
- arch/data/utility.py
- arch/tests/univariate/test_arch_in_mean.py
- arch/tests/univariate/test_forecast.py
- arch/tests/univariate/test_mean.py
- arch/tests/univariate/test_recursions.py
- arch/tests/univariate/test_volatility.py
- arch/unitroot/_shared.py
- arch/univariate/__init__.py
- arch/univariate/base.py
- arch/univariate/mean.py
- arch/univariate/recursions.pyi
- arch/univariate/recursions.pyx
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
- doc/source/changes.rst
- doc/source/changes/5.0.txt
- doc/source/univariate/mean.rst
- setup.py
Add update which is necessary to support GARCH-M models
> ENH: Add ARCH-in-mean

- arch/bootstrap/multiple_comparison.py
- arch/compat/numba.py
- arch/tests/univariate/test_arch_in_mean.py
- arch/tests/univariate/test_recursions.py
- arch/tests/univariate/test_volatility.py
- arch/typing.py
- arch/unitroot/critical_values/simulation/adf_simulation.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_joblib.py
- arch/unitroot/critical_values/simulation/adf_z_critical_values_simulation_large_cluster.py
- arch/unitroot/critical_values/simulation/dfgls_critical_values_simulation.py
- arch/univariate/base.py
- arch/univariate/mean.py
- arch/univariate/recursions.pyi
- arch/univariate/recursions.pyx
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
> ENH: Use Cython to improve AIM estimation

- arch/tests/univariate/test_arch_in_mean.py
- arch/tests/univariate/test_recursions.py
- arch/univariate/mean.py
- arch/univariate/recursions.pyi
- arch/univariate/recursions.pyx
- arch/univariate/recursions_python.py
- arch/univariate/volatility.py
Add updater to allow RM to be used in AIM models
> ENH: Add RiskMetrics2006 Updater

- arch/tests/univariate/test_arch_in_mean.py
- arch/tests/univariate/test_recursions.py
Improve coverage of edge cases
> MAINT: Update coverage

- arch/bootstrap/base.py
- arch/tests/bootstrap/test_bootstrap.py
Catch case where bias is infinite and raise an exception
closes #496
> BUG: Catch error computing bias

- arch/tests/univariate/test_recursions.py
- arch/univariate/recursions.pyx
> BUG: Correct MIDASUpdater

- arch/tests/univariate/test_forecast.py
Ensure model-based forecasts work correctly
> TST: Test model-based forecasts work

- arch/tests/univariate/test_mean.py
Add tests to ensure that models fit with limites data are identical to
those fit with first and last obs
xref #508
> TST: Add tests for first and last obs

- arch/tests/univariate/test_distribution.py
- arch/tests/univariate/test_forecast.py
- arch/univariate/distribution.py
Change nu to eta to match docs
closes  #511
> DOC: Correct parameter name

- MANIFEST.in
Ensure requirements.txt is available
> BUG: Include requirements in MANIFEST

- doc/source/_templates/autosummary/class.rst
Correct duplicate method section
> DOC: Correct repeat of method

- arch/tests/univariate/test_volatility.py
- arch/univariate/volatility.py
Ensure that the hessian step won't cross the boundary for APARCH
> ENH: Allow inference on the boundary

- arch/tests/univariate/test_recursions.py
- ci/performance.py
Use module check rather than new check
> MAINT: Small clean up to avoid import

- arch/univariate/mean.py
> Alejandro cermeno patch 1

- arch/tests/univariate/test_mean.py
> Alejandro cermeno patch 2

- arch/bootstrap/base.py
- arch/typing.py
- requirements-dev.txt
Allow both ndarray and tuple[ndarray,...]
closes #569
> BUG: Relax assertion

- arch/bootstrap/base.py
Use cast to force type for mypy
> BUG: Correct type info

- arch/tests/univariate/test_mean.py
- arch/univariate/mean.py
> TST: Add test that checks power of figarch

- doc/source/changes/5.0.txt
- setup.py
> MATIN: Add py.typed and remove unused import

- arch/univariate/mean.py
- doc/source/conf.py
> BUG: Correct FIGARCH name

- doc/source/changes/5.0.txt
> RLS: Release 5.3.0

- arch/tests/univariate/test_recursions.py
- arch/unitroot/_shared.py
- arch/univariate/distribution.py
- ci/azure/azure_template_windows.yml
- setup.py
Increase minimum to 3.8
Improve typing using pandas-stubs
> MAINT: Upgrade min Python to 3.8

- .github/workflows/generate-documentation.yml
- appveyor.yml
- arch/tests/univariate/test_mean.py
- ci/azure/azure_template_windows.yml
- ci/azure/install-posix.sh
- pyproject.toml
- setup.cfg
Make out more visible to investigate performacne issues
> TST: Make test output visible

- .github/workflows/generate-documentation.yml
- ci/azure/azure_template_windows.yml
- ci/azure/install-posix.sh
- pyproject.toml
- setup.py
Use setuptools rather than cython
> MAINT: Replace build_ext

- arch/bootstrap/base.py
- arch/tests/bootstrap/test_multiple_comparison.py
- arch/tests/covariance/test_covariance.py
- arch/tests/univariate/test_mean.py
- arch/unitroot/unitroot.py
- arch/utility/cov.py
- setup.cfg
Protect against NumPy changes
Small typign fixes
> MAINT: Protect against future changes

- arch/bootstrap/multiple_comparison.py
- arch/tests/bootstrap/test_multiple_comparison.py
- requirements-dev.txt
Allow for exact ties when removing models
Warn users for invalid use
closes #654
> ENH: Improve MCS when there is invalid use

- arch/compat/numba.py
- arch/tests/unitroot/test_unitroot.py
- arch/unitroot/unitroot.py
- arch/utility/exceptions.py
Add a performance warning when the max_lags is large
closes #606
> ENH: Add performance warning

- arch/tests/univariate/test_forecast.py
- arch/univariate/volatility.py
Add correction for reindexing changes for FIGARCH
closes #670
> BUG: Correct multistep forecasting for FIGARCH

- arch/compat/pandas.py
- arch/tests/unitroot/cointegration_data.py
- arch/tests/univariate/test_mean.py
- azure-pipelines.yml
- setup.py
Check compatability with numpy 2
Improve compatability with future pandas
> MAINT: Add NumPy 2 compat

- arch/bootstrap/multiple_comparison.py
- arch/covariance/kernel.py
- arch/tests/univariate/test_mean.py
- arch/typing.py
- arch/unitroot/_shared.py
- arch/unitroot/cointegration.py
- arch/unitroot/critical_values/simulation/engle_granger_simulation.py
- arch/unitroot/critical_values/simulation/engle_granger_simulation_process.py
- arch/univariate/base.py
- arch/univariate/distribution.py
- arch/univariate/mean.py
- arch/vendor/_decorators.py
- setup.cfg
> BUG: Correct arracy reshape in simulation

- ci/azure/install-posix.sh
Attempt to get pandas to pass on pip-pre
> CI: Add meson for pandas on pip-pre

- arch/vendor/_decorators.py
> CLN: Remove unused vendored code

- arch/vendor/_decorators.py
- examples/bootstrap_examples.ipynb
- examples/multiple-comparison_examples.ipynb
- examples/unitroot_cointegration_examples.ipynb
- examples/unitroot_examples.ipynb
- examples/univariate_forecasting_with_exogenous_variables.ipynb
- examples/univariate_using_fixed_variance.ipynb
- examples/univariate_volatility_forecasting.ipynb
- examples/univariate_volatility_modeling.ipynb
- examples/univariate_volatility_scenarios.ipynb
- pyproject.toml
- setup.cfg
Verify notebooks run
Clean setup
> MAINT: Clean up setups
